server:
  port: 8082
spring:
  application:
    name: workflow

# mybatis 打印日志
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#开启Activiti打印日志
logging:
  level:
    org.activiti.engine.impl.persistence.entity: trace
